apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-cluster-pg-node1
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /cluster-pg/data
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-cluster-pg-node2
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /cluster-pg/datacd 