apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-cluster-pg
  namespace: database
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 128Mi